### ISSUE TITLE
Not able to run the project.

### ISSUE THREAD

**Issue by Shivangi2301** [covid19india/covid19india.github.io#1831]
**Description**
I am not able to the project in my system.

Version with which I am trying to run the project.
node: 12.16.3
npm: 16.14.5

I have already installed node modules. I am getting some error while running the project. i.e after running the command _npm start_.

**Screenshots**
![image](https://user-images.githubusercontent.com/46815652/81384508-9ff85d80-90c6-11ea-9d5f-2ba672c939b9.png)

**Stacktrace**
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\spadmin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle covid19india@1.0.0~prestart: covid19india@1.0.0
6 info lifecycle covid19india@1.0.0~start: covid19india@1.0.0
7 verbose lifecycle covid19india@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle covid19india@1.0.0~start: PATH: C:\Users\spadmin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Shivangi\R & D\COVID\covid19india-react\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Program Files\nodejs\;C:\Users\spadmin\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\spadmin\.dotnet\tools;C:\Users\spadmin\AppData\Roaming\npm
9 verbose lifecycle covid19india@1.0.0~start: CWD: C:\Shivangi\R & D\COVID\covid19india-react
10 silly lifecycle covid19india@1.0.0~start: Args: [ '/d /s /c', 'react-scripts start' ]
11 silly lifecycle covid19india@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle covid19india@1.0.0~start: Failed to exec start script
13 verbose stack Error: covid19india@1.0.0 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\spadmin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\spadmin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid covid19india@1.0.0
15 verbose cwd C:\Shivangi\R & D\COVID\covid19india-react
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\spadmin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.16.3
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error covid19india@1.0.0 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the covid19india@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Thank you in Advance for help!

**Comment by nmgvikas** [comment]
The npm command when run, is looking into the C:\Shivangi path for react-scripts folder. Did you download the node modules there? Try running npm i && npm start (together) from cmd in the path C:\Shivangi\R & D\COVID\covid19india-react .

**Comment by Shivangi2301** [comment]
> The npm command when run, is looking into the C:\Shivangi path for react-scripts folder. Did you download the node modules there? Try running npm i && npm start (together) from cmd in the path C:\Shivangi\R & D\COVID\covid19india-react .

Yes, I installed node modules, which was then followed by npm start command to run the project.

**Comment by shuklaayush** [comment]
Was this resolved?

**Comment by Shivangi2301** [comment]
> Was this resolved?

No, not yet. I also tried installing latest versions of npm and node.

**Comment by rahgurung** [comment]
I think the error is because of the space in your folder name `R & D`. Try removing the space, first of all, it is always a good idea to never include whitespaces in folder and file names as it might cause parsing errors internally.

**Comment by rahgurung** [comment]
Try `RandD`, in case removing space doesn't work because `&` is a special character.

**Comment by Shivangi2301** [comment]
> Try `RandD`, in case removing space doesn't work because `&` is a special character.

I Tried this too. It didn't solve the issue.

**Comment by rahgurung** [comment]
Alright, can you show me the error with new folder name?

**Comment by Shivangi2301** [comment]
> Alright, can you show me the error with new folder name?

Sorry, my bad, using "and" instead of "&" solved it. But I am running into another issue. After running the project the homepage is not displaying the page on live site, it just shows a blue dot.

**Comment by rahgurung** [comment]
Let us know if there was any error log in the terminal further, try deleting the node_modules folder and then do 1) `npm install` 2) `npm start`.

**Comment by shuklaayush** [comment]
Closing due to inactivity

**Comment by gagangaur** [comment]
Hey, any updates on resolving I am getting an error like this and the error remains after installing typescript too.

![image](https://user-images.githubusercontent.com/40167245/91547693-ead20580-e941-11ea-88b1-0e79c6aa0c91.png)

**Comment by Shivangi2301** [comment]
> Hey, any updates on resolving I am getting an error like this and the error remains after installing typescript too.
> 
> ![image](https://user-images.githubusercontent.com/40167245/91547693-ead20580-e941-11ea-88b1-0e79c6aa0c91.png)

The problem for me was solved by renaming the folder that contained this cloned project. Try removing special characters and spaces from the folder name.

**Comment by gagangaur** [comment]
Well it's solved now I just deleted the node module folder and run those commands again.
