### ISSUE TITLE
localStorage is not accessible, when Cookies are blocked.

### ISSUE THREAD

**Issue by ankitsny** [covid19india/covid19india.github.io#2070]
Throwing exception, when cookies are blocked.
I think this can be handled when app bootstrap. 

```
3(index):1 <link rel=preload> must have a valid `as` value
(index):1 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://www.covid19india.org/:1:8410
    at https://www.covid19india.org/:1:8562
(anonymous) @ (index):1
(anonymous) @ (index):1
request.js:51 GET https://api.covid19india.org/locales/locale_en.json 404
(anonymous) @ 10.f8629b82.chunk.js:2
t.a @ 10.f8629b82.chunk.js:2
value @ 10.f8629b82.chunk.js:2
value @ 10.f8629b82.chunk.js:2
value @ 10.f8629b82.chunk.js:2
value @ 10.f8629b82.chunk.js:2
(anonymous) @ 10.f8629b82.chunk.js:2
value @ 10.f8629b82.chunk.js:2
value @ 10.f8629b82.chunk.js:2
value @ 10.f8629b82.chunk.js:2
a @ 10.f8629b82.chunk.js:2
value @ 10.f8629b82.chunk.js:2
c @ 10.f8629b82.chunk.js:2
setTimeout (async)
value @ 10.f8629b82.chunk.js:2
180 @ main.a1ebd6c4.chunk.js:1
i @ (index):1
127 @ main.a1ebd6c4.chunk.js:1
i @ (index):1
r @ (index):1
t @ (index):1
(anonymous) @ main.a1ebd6c4.chunk.js:1
react_devtools_backend.js:6 DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at t.a (https://www.covid19india.org/static/js/10.f8629b82.chunk.js:2:305656)
    at l (https://www.covid19india.org/static/js/10.f8629b82.chunk.js:2:303889)
    at https://www.covid19india.org/static/js/10.f8629b82.chunk.js:2:304729
    at Object.useMemo (https://www.covid19india.org/static/js/10.f8629b82.chunk.js:2:440932)
    at t.useMemo (https://www.covid19india.org/static/js/10.f8629b82.chunk.js:2:331099)
    at t.a (https://www.covid19india.org/static/js/10.f8629b82.chunk.js:2:304709)
    at J (https://www.covid19india.org/static/js/main.a1ebd6c4.chunk.js:1:5021)
    at Xo (https://www.covid19india.org/static/js/10.f8629b82.chunk.js:2:436038)
    at vu (https://www.covid19india.org/static/js/10.f8629b82.chunk.js:2:482444)
    at cl (https://www.covid19india.org/static/js/10.f8629b82.chunk.js:2:474977)
r @ react_devtools_backend.js:6
eu @ 10.f8629b82.chunk.js:2
n.callback @ 10.f8629b82.chunk.js:2
fo @ 10.f8629b82.chunk.js:2
ou @ 10.f8629b82.chunk.js:2
pl @ 10.f8629b82.chunk.js:2
t.unstable_runWithPriority @ 10.f8629b82.chunk.js:2
Wa @ 10.f8629b82.chunk.js:2
dl @ 10.f8629b82.chunk.js:2
Ju @ 10.f8629b82.chunk.js:2
(anonymous) @ 10.f8629b82.chunk.js:2
t.unstable_runWithPriority @ 10.f8629b82.chunk.js:2
Wa @ 10.f8629b82.chunk.js:2
Ya @ 10.f8629b82.chunk.js:2
qa @ 10.f8629b82.chunk.js:2
Xu @ 10.f8629b82.chunk.js:2
mi @ 10.f8629b82.chunk.js:2
(anonymous) @ 10.f8629b82.chunk.js:2
t @ 10.f8629b82.chunk.js:2
(anonymous) @ 10.f8629b82.chunk.js:2
value @ 10.f8629b82.chunk.js:2
(anonymous) @ 10.f8629b82.chunk.js:2
(anonymous) @ 10.f8629b82.chunk.js:2
(anonymous) @ 10.f8629b82.chunk.js:2
(anonymous) @ 10.f8629b82.chunk.js:2
value @ 10.f8629b82.chunk.js:2
(anonymous) @ 10.f8629b82.chunk.js:2
(anonymous) @ 10.f8629b82.chunk.js:2
(anonymous) @ 10.f8629b82.chunk.js:2
(anonymous) @ 10.f8629b82.chunk.js:2
Promise.then (async)
(anonymous) @ 10.f8629b82.chunk.js:2
t.a @ 10.f8629b82.chunk.js:2
value @ 10.f8629b82.chunk.js:2
value @ 10.f8629b82.chunk.js:2
value @ 10.f8629b82.chunk.js:2
value @ 10.f8629b82.chunk.js:2
(anonymous) @ 10.f8629b82.chunk.js:2
value @ 10.f8629b82.chunk.js:2
value @ 10.f8629b82.chunk.js:2
value @ 10.f8629b82.chunk.js:2
a @ 10.f8629b82.chunk.js:2
value @ 10.f8629b82.chunk.js:2
c @ 10.f8629b82.chunk.js:2
setTimeout (async)
value @ 10.f8629b82.chunk.js:2
180 @ main.a1ebd6c4.chunk.js:1
i @ (index):1
127 @ main.a1ebd6c4.chunk.js:1
i @ (index):1
r @ (index):1
t @ (index):1
(anonymous) @ main.a1ebd6c4.chunk.js:1
(index):1 Tracking Prevention blocked a Script resource from loading https://www.google-analytics.com/analytics.js.
js?id=UA-160698988-1:60 GET https://www.google-analytics.com/analytics.js net::ERR_BLOCKED_BY_CLIENT
jc @ js?id=UA-160698988-1:60
Gi @ js?id=UA-160698988-1:172
(anonymous) @ js?id=UA-160698988-1:172
Jc @ js?id=UA-160698988-1:66
Rc @ js?id=UA-160698988-1:67
Hi @ js?id=UA-160698988-1:172
cj @ js?id=UA-160698988-1:184
Ti.flush @ js?id=UA-160698988-1:188
Ti.push @ js?id=UA-160698988-1:187
Wi @ js?id=UA-160698988-1:182
config @ js?id=UA-160698988-1:193
Wj @ js?id=UA-160698988-1:200
Xj @ js?id=UA-160698988-1:201
setTimeout (async)
G @ js?id=UA-160698988-1:61
Zj @ js?id=UA-160698988-1:203
xn @ js?id=UA-160698988-1:247
(anonymous) @ js?id=UA-160698988-1:250
(anonymous) @ js?id=UA-160698988-1:250
(anonymous) @ js?id=UA-160698988-1:252
react_devtools_backend.js:6 Error during service worker registration: DOMException: Failed to register a ServiceWorker for scope ('https://www.covid19india.org/') with script ('https://www.covid19india.org/service-worker.js'): The user denied permission to use Service Worker.
r @ react_devtools_backend.js:6
(anonymous) @ main.a1ebd6c4.chunk.js:1
Promise.catch (async)
V @ main.a1ebd6c4.chunk.js:1
(anonymous) @ main.a1ebd6c4.chunk.js:1
load (async)
(anonymous) @ main.a1ebd6c4.chunk.js:1
180 @ main.a1ebd6c4.chunk.js:1
i @ (index):1
127 @ main.a1ebd6c4.chunk.js:1
i @ (index):1
r @ (index):1
t @ (index):1
(anonymous) @ main.a1ebd6c4.chunk.js:1
```

**Comment by ankitsny** [comment]
I can see `use-dark-mode` is being used to provide the theming, and [use-dark-mode](https://github.com/donavon/use-dark-mode) module internally uses [use-persisted-state](https://github.com/donavon/use-persisted-state). So I think there is a problem with [use-persisted-state](https://github.com/donavon/use-persisted-state) module.

Check if there is an alternative of `use-dark-mode`.

**Comment by shuklaayush** [comment]
It would be great if you could post an issue on the [use-dark-mode](https://github.com/donavon/use-dark-mode) repository as well. Let's see if they can fix this.

**Comment by ankitsny** [comment]
Done, but it seems there is no one actively maintaining the repo.
Last version was released a year ago
