### ISSUE TITLE
Error in bash project-maps.sh

### ISSUE THREAD

**Issue by alkuhlani** [covid19india/covid19india.github.io#2330]
I tried to bash the script [project-maps.sh](https://github.com/covid19india/covid19india-react/blob/master/scripts/project-maps.sh) but I get these errors:
topomerge: command not found
topo2geo: command not found
geoproject: command not found
geoproject: command not found
Also I tried to install them by npm install - but I get errors again

Note: I delete the maps in the projected_maps before I start the bash

Is there are another way to run the project-maps.sh file

Thank you in advance

**Comment by shuklaayush** [comment]
Install using `npm install -g ...` and make sure that the directory where the binaries are installed is in the PATH env variable. [This](https://superuser.com/questions/1081769/after-npm-install-g-command-still-not-found) might be of help

**Comment by alkuhlani** [comment]
Please check these  
http://registry.npmjs.org/topomerge
http://registry.npmjs.org/topo2geo
http://registry.npmjs.org/geoproject
the result is 

{"error":"Not found"}

**Comment by shuklaayush** [comment]
The binaries are in these packages. Try after installing these
https://www.npmjs.com/package/d3-geo-projection
https://www.npmjs.com/package/topojson-client
https://www.npmjs.com/package/topojson-server

**Comment by alkuhlani** [comment]
I tried to install them, and they had been installed.
Everything works fine, except running the .sh file.
I get the same error 
topomerge: command not found
topo2geo: command not found
geoproject: command not found

and I do not know why!

**Comment by alkuhlani** [comment]
Now I get this error
```

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Socket.<anonymous> (/usr/lib/node_modules/d3-geo-projection/bin/read.js:13:48)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Socket.<anonymous> (/usr/lib/node_modules/topojson-server/bin/geo2topo:107:46)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
project-maps.sh: 14: project-maps.sh: topo2geo: not found
undefined:1

```

**Comment by shuklaayush** [comment]
> `topo2geo: not found`

Looks like `topo2geo` is either not installed or not in PATH. You can check if it's working by running `topo2geo -V` on the terminal. Maybe try reinstalling `topojson-client`

**Comment by alkuhlani** [comment]
@shuklaayush 
Thank you I really appreciate your support, I added all nodes to PATH, and the `node -v` is working fine
by this way:- 
1. cd /usr/bin/
2. sudo ln -s nodejs node
I do it with all of these node (`d3-geo-projection,topojson-client,topojson-server,topo2geo,districts,geoproject,geo2topo,districts,prettier`)

Now I get this error 😢
```
module.js:550
    throw err;
    ^

Error: Cannot find module '/usr/bin/districts=-'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
module.js:550
    throw err;
    ^

Error: Cannot find module '/usr/bin/d3.geoMercator().fitSize([432, 488], d)'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
module.js:550
    throw err;
    ^

Error: Cannot find module '/usr/bin/districts=-'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
module.js:550
    throw err;
    ^

Error: Cannot find module '/usr/bin/districts=-'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
module.js:550
    throw err;
    ^

Error: Cannot find module '/usr/bin/d3.geoMercator().fitSize([432, 488], d)'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
module.js:550
    throw err;
    ^

Error: Cannot find module '/usr/bin/districts=-'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
module.js:550
    throw err;
    ^

Error: Cannot find module '/usr/bin/states=districts'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
mv: cannot stat '/home/frappe/covid/covid19india-react/scripts/../public/projected_maps/india_merged.json': No such file or directory
prettier: bad option: --loglevel

```

**Comment by alkuhlani** [comment]
@shuklaayush, I do the below command:-
```
sudo npm install -g d3-geo-projection
sudo npm install -g topojson-server
sudo npm install -g topojson-client
```

and every thing goes OK 🙂, I'm so so happy 😅,
Now I get only this message
`prettier: bad option: --loglevel`

Thank you for everything.
