### ISSUE TITLE
npm i error

### ISSUE THREAD

**Issue by ssadev** [covid19india/covid19india.github.io#99]
sk@sk-desktop:~/Desktop/react/covid19india-react$ npm i
loadDep:vx -> 304         / |#############--------------------------------------------------|
WARN engine @testing-library/jest-dom@5.1.1: wanted: {"node":">=8","npm":">=6","yarn":">=1"} (loadDep:vx -> get         - |#############--------------------------------------------------|
WARN engine @testing-library/react@10.0.1: wanted: {"node":">=10"} (current: {"node":"8.10.0",npm WARN deprecated topojson@3.0.2: Use topojson-client, topojson-server or topojson-simplify directly.
loadDep:@types/testing-li \ |#############--------------------------------------------------|
WARN engine @testing-library/dom@7.1.1: wanted: {"node":">=10"} (current: {"node":"8.10.0","npnpm ERR! Linux 5.0.0-23-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sk/Desktop/react/covid19india-react/npm-debug.log

**Comment by ssadev** [comment]
After updating node by `sudo npm install -g n && sudo n latest ` this error got fixed
